// Types
export type {
  Ink,
  GameMode,
  CardType,
  LorcanaCard,
  SynergyCategory,
  PlaystyleId,
  Playstyle,
  DirectSynergyRule,
  PlaystyleSynergyRule,
  SynergyRule,
  SynergyMatch,
  SynergyMatchDisplay,
  SynergyGroup,
  PairSynergyConnection,
  DetailedPairSynergy,
} from './types';

// Format
export {MIN_CORE_SET, isCoreSet} from './constants';

// Engine
export {
  SynergyEngine,
  synergyEngine,
  SynergyCache,
  synergyCache,
  synergyRules,
  getAllRules,
  getRulesByCategory,
  getRulesByPlaystyle,
  getRuleById,
  getAllPlaystyles,
  getPlaystyleById,
  LOCATION_ROLE_CHIP_LABELS,
  LOCATION_ROLE_DESCRIPTIONS,
  LOCATION_ROLE_TOOLTIP,
} from './engine';
export type {SynergyEngineOptions, CachedSynergyResult} from './engine';

// Utilities (for custom rule authors)
export {
  isDualInk,
  getInks,
  canShareDeck,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getShiftBaseNames,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  isCardType,
  getShiftType,
  hasAnyShift,
  getInkDropGain,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getSacrificeRoles,
  isSacrificeCard,
  getSelfDiscardRoles,
  isSelfDiscardCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  transformCard,
  transformCards,
  cardSlug,
  cardPath,
  canonicalizeCardLine,
  canonicalizeCardText,
  canonicalizeCardFullText,
  findGlyphWords,
  NAMED_REFERENCE,
  getToyRoles,
  isToyCard,
  getDwarfsRoles,
  isDwarfsCard,
  getLoreDenialRoles,
  isLoreDenialCard,
  getFloodbornRoles,
  isFloodbornCard,
  getHunnyRoles,
  isHunnyCard,
  getRedPandaRoles,
  isRedPandaCard,
  getItemRoles,
  isItemCard,
  getHealRoles,
  isHealCard,
  getExertRoles,
  isExertCard,
  isExertConsumePayoff,
  getBounceRoles,
  getBounceTargetGate,
  bounceGateAdmits,
  isBounceCard,
  getInkDropRoles,
  isInkDropCard,
  isDropSpendRider,
  isDropRemoveTrigger,
  isDropHoldPayoff,
  isDropSink,
  isRepeatingDropMaker,
  isOpponentGatedDrop,
  getTribalRoles,
  isTribalCard,
  TRIBAL_SPECS,
  isSteadyAimAnchor,
  getActionDamage,
  isMeridaDamageAction,
  isMultiTargetDamageAction,
  isBeckonAnchor,
  getBeckonEnablerTier,
  isBeckonEnabler,
  MECHANICS,
  STRUCTURAL_MECHANICS,
  MECHANIC_BY_ID,
  STRUCTURAL_ROLE_TO_MECHANIC,
  getCardMechanics,
  mechanicLabel,
  mechanicDescription,
} from './utils';
export {TUNING, type TuningConfig, type TierText} from './data/tuning';
export type {
  LocationRole,
  ShiftType,
  ShiftPayment,
  NamedEffectTier,
  DiscardRole,
  SacrificeRole,
  SelfDiscardRole,
  RampRole,
  ToyRole,
  DwarfsRole,
  LoreDenialRole,
  FloodbornRole,
  HunnyRole,
  RedPandaRole,
  ItemRole,
  HealRole,
  ExertRole,
  BounceRole,
  BounceTargetGate,
  InkDropRole,
  BeckonEnablerTier,
  TribalRole,
  TribalSpec,
  LorcanaJSONCard,
} from './utils';
