// Types
export type {
  Ink,
  GameMode,
  CardType,
  LorcanaCard,
  SynergyCategory,
  PlaystyleId,
  Playstyle,
  DirectSynergyRule,
  PlaystyleSynergyRule,
  SynergyRule,
  SynergyMatch,
  SynergyMatchDisplay,
  SynergyGroup,
  PairSynergyConnection,
  DetailedPairSynergy,
} from './types';

// Engine
export {
  SynergyEngine,
  synergyEngine,
  SynergyCache,
  synergyCache,
  synergyRules,
  getAllRules,
  getRulesByCategory,
  getRulesByPlaystyle,
  getRuleById,
  getAllPlaystyles,
  getPlaystyleById,
  LOCATION_ROLE_CHIP_LABELS,
  LOCATION_ROLE_DESCRIPTIONS,
  LOCATION_ROLE_TOOLTIP,
  DISCARD_ROLE_CHIP_LABELS,
  DISCARD_ROLE_DESCRIPTIONS,
  RAMP_ROLE_CHIP_LABELS,
  RAMP_ROLE_DESCRIPTIONS,
} from './engine';
export type {SynergyEngineOptions, CachedSynergyResult} from './engine';

// Utilities (for custom rule authors)
export {
  isDualInk,
  getInks,
  canShareDeck,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  isCardType,
  getShiftType,
  hasAnyShift,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  transformCard,
  transformCards,
  getToyRoles,
  isToyCard,
} from './utils';
export type {LocationRole, ShiftType, NamedEffectTier, DiscardRole, RampRole, ToyRole, LorcanaJSONCard} from './utils';
