// Types
export type {
  Ink,
  GameMode,
  CardType,
  LorcanaCard,
  SynergyCategory,
  PlaystyleId,
  Playstyle,
  DirectSynergyRule,
  PlaystyleSynergyRule,
  SynergyRule,
  SynergyMatch,
  SynergyMatchDisplay,
  SynergyGroup,
  PairSynergyConnection,
  DetailedPairSynergy,
} from './types';

// Engine
export {
  SynergyEngine,
  synergyEngine,
  SynergyCache,
  synergyCache,
  synergyRules,
  getAllRules,
  getRulesByCategory,
  getRulesByPlaystyle,
  getRuleById,
  getAllPlaystyles,
  getPlaystyleById,
  LOCATION_ROLE_CHIP_LABELS,
  LOCATION_ROLE_DESCRIPTIONS,
  LOCATION_ROLE_TOOLTIP,
} from './engine';
export type {SynergyEngineOptions, CachedSynergyResult} from './engine';

// Utilities (for custom rule authors)
export {
  isDualInk,
  getInks,
  canShareDeck,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getShiftBaseNames,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  isCardType,
  getShiftType,
  hasAnyShift,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getSacrificeRoles,
  isSacrificeCard,
  getSelfDiscardRoles,
  isSelfDiscardCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  transformCard,
  transformCards,
  getToyRoles,
  isToyCard,
  getDwarfsRoles,
  isDwarfsCard,
  getLoreDenialRoles,
  isLoreDenialCard,
  getFloodbornRoles,
  isFloodbornCard,
  getHunnyRoles,
  isHunnyCard,
  getRedPandaRoles,
  isRedPandaCard,
  getItemRoles,
  isItemCard,
  MECHANICS,
  STRUCTURAL_MECHANICS,
  MECHANIC_BY_ID,
  STRUCTURAL_ROLE_TO_MECHANIC,
  getCardMechanics,
  mechanicLabel,
  mechanicDescription,
} from './utils';
export type {
  LocationRole,
  ShiftType,
  NamedEffectTier,
  DiscardRole,
  SacrificeRole,
  SelfDiscardRole,
  RampRole,
  ToyRole,
  DwarfsRole,
  LoreDenialRole,
  FloodbornRole,
  HunnyRole,
  RedPandaRole,
  ItemRole,
  LorcanaJSONCard,
} from './utils';
