export {
  isDualInk,
  getInks,
  canShareDeck,
  normalizeCardText,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getShiftBaseNames,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  getShiftType,
  hasAnyShift,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getSacrificeRoles,
  isSacrificeCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  getCostReductionTarget,
  costReductionTargetsOverlap,
  getToyRoles,
  isToyCard,
  getDwarfsRoles,
  isDwarfsCard,
  getFloodbornRoles,
  isFloodbornCard,
  getHunnyRoles,
  isHunnyCard,
  getRedPandaRoles,
  isRedPandaCard,
  isBoostBeneficiaryLocation,
  getLoreDenialRoles,
  isLoreDenialCard,
  LORE_LOSS_PATTERN,
} from './cardHelpers.js';
export type {
  LocationRole,
  ShiftType,
  NamedEffectTier,
  DiscardRole,
  SacrificeRole,
  RampRole,
  CostReductionTarget,
  ToyRole,
  DwarfsRole,
  FloodbornRole,
  HunnyRole,
  RedPandaRole,
  LoreDenialRole,
} from './cardHelpers.js';

export {isCardType} from './typeGuards.js';

export {
  MECHANICS,
  STRUCTURAL_MECHANICS,
  MECHANIC_BY_ID,
  STRUCTURAL_ROLE_TO_MECHANIC,
  getCardMechanics,
  mechanicLabel,
  mechanicDescription,
} from './mechanics.js';
export type {Mechanic} from './mechanics.js';

export {transformCard, transformCards} from './cardTransformer.js';
export type {LorcanaJSONCard} from './cardTransformer.js';
