export {
  isDualInk,
  getInks,
  canShareDeck,
  normalizeCardText,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  getShiftType,
  hasAnyShift,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getSacrificeRoles,
  isSacrificeCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  getCostReductionTarget,
  costReductionTargetsOverlap,
  getToyRoles,
  isToyCard,
  getDwarfsRoles,
  isDwarfsCard,
  isBoostBeneficiaryLocation,
  getLoreDenialRoles,
  isLoreDenialCard,
  LORE_LOSS_PATTERN,
} from './cardHelpers.js';
export type {
  LocationRole,
  ShiftType,
  NamedEffectTier,
  DiscardRole,
  SacrificeRole,
  RampRole,
  CostReductionTarget,
  ToyRole,
  DwarfsRole,
  LoreDenialRole,
} from './cardHelpers.js';

export {isCardType} from './typeGuards.js';

export {transformCard, transformCards} from './cardTransformer.js';
export type {LorcanaJSONCard} from './cardTransformer.js';
