export {
  isDualInk,
  getInks,
  canShareDeck,
  normalizeCardText,
  textContains,
  hasKeyword,
  hasKeywordExact,
  hasClassification,
  getBaseName,
  getShiftBaseNames,
  getKeywordValue,
  isSong,
  isCharacter,
  isAction,
  isItem,
  isLocation,
  hasNegativeTargeting,
  hasPositiveClassificationEffect,
  isLocationSupportCard,
  getLocationRoles,
  LOCATION_PATTERNS,
  getShiftType,
  hasAnyShift,
  getInkDropGain,
  getNamedReferences,
  classifyNamedEffect,
  NAMED_EFFECT_SCORES,
  getDiscardRoles,
  isDiscardCard,
  getSacrificeRoles,
  isSacrificeCard,
  getSelfDiscardRoles,
  isSelfDiscardCard,
  getRampRoles,
  isRampCard,
  isDeckRamp,
  isRepeatingTrigger,
  getCostReductionTarget,
  costReductionTargetsOverlap,
  getToyRoles,
  isToyCard,
  getDwarfsRoles,
  isDwarfsCard,
  getFloodbornRoles,
  isFloodbornCard,
  getHunnyRoles,
  isHunnyCard,
  getRedPandaRoles,
  isRedPandaCard,
  getItemRoles,
  isItemCard,
  getHealRoles,
  isHealCard,
  getExertRoles,
  isExertCard,
  isExertConsumePayoff,
  getBounceRoles,
  getBounceTargetGate,
  bounceGateAdmits,
  isBounceCard,
  getTribalRoles,
  isTribalCard,
  TRIBAL_SPECS,
  isSteadyAimAnchor,
  getActionDamage,
  isMeridaDamageAction,
  isMultiTargetDamageAction,
  isBeckonAnchor,
  getBeckonEnablerTier,
  isBeckonEnabler,
  isBoostBeneficiaryLocation,
  getLoreDenialRoles,
  isLoreDenialCard,
  LORE_LOSS_PATTERN,
} from './cardHelpers.js';
export type {
  LocationRole,
  ShiftType,
  ShiftPayment,
  NamedEffectTier,
  DiscardRole,
  SacrificeRole,
  SelfDiscardRole,
  RampRole,
  CostReductionTarget,
  ToyRole,
  DwarfsRole,
  FloodbornRole,
  HunnyRole,
  RedPandaRole,
  ItemRole,
  HealRole,
  ExertRole,
  BounceRole,
  BounceTargetGate,
  BeckonEnablerTier,
  TribalRole,
  TribalSpec,
  LoreDenialRole,
} from './cardHelpers.js';

export {
  getInkDropRoles,
  isInkDropCard,
  isDropSpendRider,
  isDropRemoveTrigger,
  isDropHoldPayoff,
  isDropSink,
  isRepeatingDropMaker,
  isOpponentGatedDrop,
} from './inkDrops.js';
export type {InkDropRole} from './inkDrops.js';

export {isCardType} from './typeGuards.js';

export {
  MECHANICS,
  STRUCTURAL_MECHANICS,
  MECHANIC_BY_ID,
  STRUCTURAL_ROLE_TO_MECHANIC,
  getCardMechanics,
  mechanicLabel,
  mechanicDescription,
} from './mechanics.js';
export type {Mechanic} from './mechanics.js';

export {transformCard, transformCards} from './cardTransformer.js';
export type {LorcanaJSONCard} from './cardTransformer.js';

export {cardSlug, cardPath} from './cardSlug.js';
