// Generates .design-sync/entry.tsx — the bundle entry for design-sync.
//
// WHY THIS EXISTS: inkweave-web is an APP, not a published component library.
// It has no `main`/`module`/`exports` and no component dist/, so the converter's
// storybook shape (which calls resolveDistEntry WITHOUT a synth fallback) would
// hard-exit [NO_DIST]. This barrel is that entry: esbuild bundles it into
// window.Inkweave, which is what claude.ai/design's agent builds with AND what
// story-imports.mjs rule 2 redirects relative component imports to.
//
// Only components the barrel exports survive the roster filter
// (`src.components.filter(c => exported.has(c.name))` in package-build.mjs) —
// a missing export silently drops the component with [TITLE_UNMAPPED].
//
// Re-run after adding/removing/renaming a storied component:
//   node .design-sync/gen-entry.mjs
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname, basename, relative } from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const WEB = join(HERE, '..', 'apps', 'web');
const SRC = join(WEB, 'src');

const walk = (dir, out = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
};

const slash = (p) => p.replace(/\\/g, '/');
const files = walk(SRC).map(slash);
const stories = files.filter((p) => p.endsWith('.stories.tsx')).sort();

const entries = [];
const titleMap = {};
const problems = [];

for (const story of stories) {
  const txt = readFileSync(story, 'utf8');
  const title = /title:\s*['"`]([^'"`]+)['"`]/.exec(txt)?.[1] ?? null;
  const base = basename(story, '.stories.tsx');
  const dir = dirname(story);

  // The roster name the converter derives: last title segment, whitespace stripped.
  const rosterName = title ? title.split('/').pop().replace(/\s+/g, '') : base;

  // The real component identifier, in priority order: the `component:` field
  // (authoritative — it's the actual imported binding), else the filename.
  const declared = /component:\s*([A-Za-z0-9_]+)/.exec(txt)?.[1] ?? null;

  const impl = [
    join(dir, base + '.tsx'),
    join(dir, base, 'index.tsx'),
  ].map(slash).find((p) => existsSync(p));

  if (!impl) {
    // Documentation-only stories (no component module to export).
    problems.push({ kind: 'no-impl', story: relative(SRC, story), rosterName });
    if (rosterName) titleMap[rosterName] = null;
    continue;
  }

  const implTxt = readFileSync(impl, 'utf8');
  // Prefer an export name the impl actually declares.
  const declares = (n) =>
    n && new RegExp(`export\\s+(?:const|let|var|function|class)\\s+${n}\\b`).test(implTxt);
  const reexports = (n) =>
    n && new RegExp(`export\\s*\\{[^}]*\\b${n}\\b`).test(implTxt);

  let name = null;
  if (declares(declared) || reexports(declared)) name = declared;
  else if (declares(rosterName) || reexports(rosterName)) name = rosterName;
  else if (declares(base) || reexports(base)) name = base;

  if (!name) {
    problems.push({
      kind: 'no-named-export',
      story: relative(SRC, story),
      rosterName,
      declared,
      impl: relative(SRC, impl),
    });
    continue;
  }

  // Roster name must resolve to the exported name; titleMap bridges any gap.
  if (rosterName !== name) titleMap[rosterName] = name;

  entries.push({ name, impl });
}

// Dedupe by exported name (several stories can target one component).
const byName = new Map();
for (const e of entries) if (!byName.has(e.name)) byName.set(e.name, e.impl);

const lines = [...byName.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, impl]) => `export {${name}} from '${slash(relative(HERE, impl)).replace(/\.tsx$/, '')}';`);

const header = `// GENERATED by .design-sync/gen-entry.mjs — do not edit by hand.
// The design-sync bundle entry: every storied component, re-exported for
// window.Inkweave. Regenerate after adding/renaming a storied component.
// ${byName.size} components.
`;

writeFileSync(join(HERE, 'entry.tsx'), header + lines.join('\n') + '\n');

console.log(`entry.tsx: ${byName.size} components exported`);
console.log(`titleMap entries needed: ${Object.keys(titleMap).length}`);
console.log(JSON.stringify(titleMap, null, 2));
if (problems.length) {
  console.log(`\nproblems (${problems.length}):`);
  for (const p of problems) console.log(' ', p.kind, '|', p.story, '|', JSON.stringify(p));
}
