// Generates .design-sync/styles-entry.css — the stylesheet cfg.cssEntry points at.
//
// WHY THIS EXISTS: `react-loading-skeleton/dist/skeleton.css` is imported by
// apps/web/src/main.tsx and by .storybook/preview.tsx, but NOT by
// apps/web/src/index.css. index.css is what cfg.cssEntry pointed at, so
// `.react-loading-skeleton` never reached _ds_bundle.css and EVERY <Skeleton>
// rendered as a zero-size, background-less span — in the previews AND in every
// design the claude.ai/design agent builds.
//
// It has to be a real CONCATENATION, not an @import wrapper: package-build.mjs
// consumes cssEntry with a raw readFileSync + append (it is not bundled), so an
// `@import` would ship verbatim into _ds_bundle.css and 404 in the design
// project, fixing nothing.
//
// Generated (and gitignored) rather than committed so it cannot drift from
// index.css. Wired into cfg.buildCmd, so the driver regenerates it every build.
//
// Run: node .design-sync/gen-css.mjs
import {readFileSync, writeFileSync, existsSync} from 'node:fs';
import {dirname, join} from 'node:path';

const HERE = dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const WEB = join(HERE, '..', 'apps', 'web');

const parts = [];

// 1. skeleton.css FIRST, so index.css (and component styles) can override it.
const skeleton = join(WEB, 'node_modules', 'react-loading-skeleton', 'dist', 'skeleton.css');
if (!existsSync(skeleton)) {
  console.error(`[GEN_CSS] react-loading-skeleton not found at ${skeleton} — run pnpm install`);
  process.exit(1);
}
parts.push('/* from react-loading-skeleton/dist/skeleton.css */', readFileSync(skeleton, 'utf8'));

// 2. The app's own base layer.
const index = join(WEB, 'src', 'index.css');
if (!existsSync(index)) {
  console.error(`[GEN_CSS] ${index} not found`);
  process.exit(1);
}
parts.push('/* from apps/web/src/index.css */', readFileSync(index, 'utf8'));

// 3. Preview-harness rules for cfg.provider's InkweaveDesignRoot wrapper.
//
// These need a DESCENDANT selector, so they cannot be inline styles on the
// component. The height is the load-bearing part: a `position: fixed` overlay's
// containing block is the nearest transformed ancestor, and InkweaveDesignRoot
// is transformed — so if its height is INDEFINITE (`min-height: 100%` against an
// auto-height chain) it collapses to content height, which for an all-fixed
// component is zero. `inset: 0` then resolved to 900x32 instead of 900x675 and
// clipped CardOverviewModal, MechanicsBottomSheet, VoteConfirmation and VoteToast
// off-screen entirely.
//
// 100vh matches the storybook decorator (`minHeight: '100vh', padding: 0`), which
// is the render being compared against. It is scoped OFF inside .ds-cell because
// a viewport-tall wrapper in a grid cell would stretch every cell in the product
// card — the original, correct objection to setting it globally.
parts.push(
  '/* design-sync preview harness — cfg.provider wrapper */',
  `.inkweave-ds-root { min-height: 100vh; padding: 0; }
.ds-cell .inkweave-ds-root { min-height: 100%; }`,
);

const out = join(HERE, 'styles-entry.css');
writeFileSync(
  out,
  '/* GENERATED by .design-sync/gen-css.mjs — do not edit. */\n' + parts.join('\n\n') + '\n',
);
console.log(`styles-entry.css: ${parts.length / 2} stylesheets concatenated`);
